# Generated by Django 5.1.5 on 2025-02-05 14:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical1', '0003_docteur_delete_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='docteur',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='docteur',
            name='localisation',
            field=models.CharField(choices=[('Ariana', 'Ariana'), ('Béja', 'Béja'), ('Ben Arous', 'Ben Arous'), ('Bizerte', 'Bizerte'), ('Gabès', 'Gabès'), ('Gafsa', 'Gafsa'), ('Jendouba', 'Jendouba'), ('Kairouan', 'Kairouan'), ('Kasserine', 'Kasserine'), ('Kébili', 'Kébili'), ('Kef', 'Kef'), ('Mahdia', 'Mahdia'), ('Manouba', 'Manouba'), ('Médenine', 'Médenine'), ('Monastir', 'Monastir'), ('Nabeul', 'Nabeul'), ('Sfax', 'Sfax'), ('Sidi Bouzid', 'Sidi Bouzid'), ('Siliana', 'Siliana'), ('Sousse', 'Sousse'), ('Tataouine', 'Tataouine'), ('Tozeur', 'Tozeur'), ('Tunis', 'Tunis'), ('Zaghouan', 'Zaghouan')], max_length=100),
        ),
        migrations.AlterField(
            model_name='docteur',
            name='specialite',
            field=models.CharField(choices=[('Généraliste', 'Généraliste'), ('Cardiologue', 'Cardiologue'), ('Dermatologue', 'Dermatologue'), ('Pédiatre', 'Pédiatre'), ('Ophtalmologue', 'Ophtalmologue'), ('Gynécologue', 'Gynécologue'), ('Orthopédiste', 'Orthopédiste'), ('Neurologue', 'Neurologue'), ('Psychiatre', 'Psychiatre'), ('Urologue', 'Urologue')], max_length=100),
        ),
        migrations.AlterField(
            model_name='docteur',
            name='telephone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
