# Generated by Django 5.1.5 on 2025-02-08 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical1', '0005_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='date_joined',
        ),
    ]
