# Generated by Django 5.1.5 on 2025-03-19 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical1', '0006_remove_client_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut_lundi', models.TimeField(blank=True, null=True)),
                ('fin_lundi', models.TimeField(blank=True, null=True)),
                ('debut_mardi', models.TimeField(blank=True, null=True)),
                ('fin_mardi', models.TimeField(blank=True, null=True)),
                ('debut_mercredi', models.TimeField(blank=True, null=True)),
                ('fin_mercredi', models.TimeField(blank=True, null=True)),
                ('debut_jeudi', models.TimeField(blank=True, null=True)),
                ('fin_jeudi', models.TimeField(blank=True, null=True)),
                ('debut_vendredi', models.TimeField(blank=True, null=True)),
                ('fin_vendredi', models.TimeField(blank=True, null=True)),
                ('debut_samedi', models.TimeField(blank=True, null=True)),
                ('fin_samedi', models.TimeField(blank=True, null=True)),
                ('debut_dimanche', models.TimeField(blank=True, null=True)),
                ('fin_dimanche', models.TimeField(blank=True, null=True)),
                ('docteur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='medical1.docteur')),
            ],
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Confirmé', 'Confirmé'), ('Annulé', 'Annulé')], default='En attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('docteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='medical1.docteur')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendezvous', to='medical1.client')),
            ],
        ),
    ]
